/* Sven Coop Constants
*
* This file is provided as is (no warranties).
*/

#if defined _svencoop_const_included
  #endinput
#endif
#define _svencoop_const_included

// The PDATA defines are for using with FM
// The SVEN_WEP_* defines are for sc_ weapon natives
// Please, use the provided stocks.

#define PDATA_FRAGS 0x9
#define PDATA_DEATHS 0x21B0
#define PDATA_ALLY 0x28

#define SVEN_WEP_9MM 0
#define PDATA_9MM 0x216D
#define PDATA_9MM2 0x218D

#define SVEN_WEP_SHOTGUN 1
#define PDATA_SHOTGUN 0x216E
#define PDATA_SHOTGUN2 0x218E

#define SVEN_WEP_RPG 2
#define PDATA_RPG 0x2195
#define PDATA_RPG2 0x21B5

#define SVEN_WEP_RADIO 3
#define PDATA_RADIO 0x217A
#define PDATA_RADIO2 0x219A

#define SVEN_WEP_SNARK 4
#define PDATA_SNARK 0x217A
#define PDATA_SNARK2 0x219A
	