// vim: set ts=4 sw=4 tw=99 noet:
//
// AMX Mod X, based on AMX Mod by Aleksander Naszko ("OLO").
// Copyright (C) The AMX Mod X Development Team.
//
// This software is licensed under the GNU General Public License, version 3 or higher.
// Additional exceptions apply. For full license details, see LICENSE.txt or visit:
//     https://alliedmods.net/amxmodx-license

#if defined _amxmodx_version_included
	#endinput
#endif
#define _amxmodx_version_included

#define AMXX_VERSION		1.83
#define AMXX_VERSION_NUM	183
stock const AMXX_VERSION_STR[] = "1.8.3-manual";
