/* AMX Mod X constants
*
* by the AMX Mod X Development Team
*  originally developed by OLO
*
* This file is provided as is (no warranties).
*/

#if defined _svnversion_included
  #endinput
#endif
#define _svnversion_included

#tryinclude <amxmodx_version>
#if !defined _amxmodx_version_included
  #define AMXX_VERSION		1.83
  #define AMXX_VERSION_NUM	183
  stock const AMXX_VERSION_STR[] = "1.8.3-dev";
#endif
