#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_VERSION_STRING		"$PMAJOR$.$PMINOR$.$PREVISION$$BUILD_STRING$"
#define SVN_VERSION_DWORD		$PMAJOR$,$PMINOR$,$PREVISION$,0
#define SVN_VERSION_PRODUCT		"$PMAJOR$.$PMINOR$.$PREVISION$"
#define SVN_BUILD_ID			SVN_VERSION_STRING " $BUILD_ID$"

#endif //_INCLUDE_SVN_VERSION_H_
