#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_VERSION_STRING		"1.8.0.3648"
#define SVN_VERSION_DWORD		1,8,0,3648
#define SVN_VERSION_PRODUCT		"1.8.0"

#endif //_INCLUDE_SVN_VERSION_H_
