#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_VERSION_STRING		"1.8.2-dev"
#define SVN_VERSION_DWORD		1,8,2,0
#define SVN_VERSION_PRODUCT		"1.8.2"
#define SVN_BUILD_ID			SVN_VERSION_STRING " 9:7ff502465eae"

#endif //_INCLUDE_SVN_VERSION_H_
