del .\*.~pas
del .\*.dcu
del .\*.~ddp
del .\*.ddp
del .\*.~dpr
del .\*.~dfm
del .\*.~dpr
del .\*.map
del .\*.drc
del .\bugreport.txt
del .\plugins\*.~xfm
del .\plugins\*.~pas
del .\plugins\*.dcu
del .\plugins\*.~ddp
del .\plugins\*.ddp
del .\plugins\*.~dpr
del .\plugins\*.~dfm
del .\plugins\*.~dpr
del .\plugins\*.map
del .\plugins\*.drc
del .\plugins\*.~xfm
upx AMXX_Studio.exe