/* BrainBread Fun Module Constants
 *
 * (c) 2005, XxAvalanchexX (converted to module by Rukia)
 *
 * This file is provided as is (no warranties).
 */

#if defined _brainbread_const_included
  #endinput
#endif
#define _brainbread_const_included


#define SPRAY_BSPRITZ	1
#define SPRAY_BGUSH	2
#define SPRAY_SMOKEPUFF	4
#define SPRAY_EXPLOSION	5

#define DOT_GREEN	1
#define DOT_RED	2
#define DOT_WHITE	3
#define DOT_LTBLUE	4
#define DOT_BLUE	5
#define DOT_ORANGE	6
#define DOT_FLYELLOW	7
#define DOT_FLGREEN	8
