name: Build AMX Mod X Debug

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Debug Version
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 克隆 Half-Life SDK 仓库
      - name: Clone Half-Life SDK
        run: |
          git clone https://github.com/alliedmodders/hlsdk.git third_party/halflife-sdk

      # 列出 Half-Life SDK 文件
      - name: List Half-Life SDK files
        run: dir third_party/halflife-sdk /s /b

      # 设置 MSBuild 环境
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # 编译 Debug 版本
      - name: Build Debug version
        run: |
          msbuild modules/cstrike/cstrike/msvc12/cstrike.sln /p:Configuration=Debug

      # 查看生成的产物
      - name: List build artifacts
        run: dir /s /b

      # 保存构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cstrike-debug-build
          path: modules/cstrike/cstrike/msvc12/Debug/
