name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  Label:
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler/labeler.yml