name: Build AMX Mod X Debug

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Debug Version
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 MSBuild 环境
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # 自动重新定向工具集
      - name: Retarget solution to v143
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe > msbuild_path.txt
          set /p MSBUILD_PATH=<msbuild_path.txt
          "%MSBUILD_PATH%" amxmodx/msvc12/amxmodx_mm.sln /p:PlatformToolset=v143 /p:Configuration=Debug

      # 编译 Debug 版本
      - name: Build Debug version
        run: |
          msbuild amxmodx/msvc12/amxmodx_mm.sln /p:Configuration=Debug

      # 查看生成的产物
      - name: List build artifacts
        run: dir /s /b

      # 保存构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: amxmodx-debug-build
          path: Debug/
