name: Build AMX Mod X Debug

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Debug Version
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Visual Studio 环境
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      # 编译 Debug 版本
      - name: Build Debug version
        run: |
          msbuild your_project.sln /p:Configuration=Debug

      # 查看生成的产物
      - name: List build artifacts
        run: dir /s /b

      # 保存构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: amxmodx-debug-build
          path: path\to\your\output\directory
